### ISSUE TITLE
Erro na regex de horário

### ISSUE THREAD

**Issue by adzubla** [OpenBanking-Brasil/areadesenvolvedor-fase1#31]
A expressão regular usada para hora está com problemas. Para o valor 10:20:30Z não dá o match() da string completa (apesar do find() ser verdadeiro). Além disso permite que apenas "Z" seja um valor válido.

Atual:

    ^(?:[01]\\d|2[0123]):(?:[012345]\\d):(?:[012345]\\d)|Z$|^NA$

A correção consiste em tirar o | antes do Z:

    ^(?:[01]\\d|2[0123]):(?:[012345]\\d):(?:[012345]\\d)Z$|^NA$

**Comment by adzubla** [comment]
Esse pattern aparece na api "channels"

**Comment by luankevinferreira** [comment]
Agradecemos sua contribuição, porém este repositório ainda não está liberado formalmente para contribuições externas, portanto todas as correções são aplicadas somente após avaliação das instituições, peço que você solicite a correção via Service Desk em: https://openbankingbrasil.github.io/suporte/
