### ISSUE TITLE
Tipo do Objeto brand/companies/personalUnarrangedAccountOverdraft

### ISSUE THREAD

**Issue by davidburil** [OpenBanking-Brasil/areadesenvolvedor-fase1#38]
Sobre a API de Serviços de Adiantamento a Depositante, identificamos uma divergência em dois objetos semelhantes.

Na parte do _Adiantamento a Depositante Pessoa Natural_, o objeto `brand/companies/personalUnarrangedAccountOverdraft` está definido como uma lista na estrutura de exemplo do json.

E na parte _Adiantamento a Depositante Pessoa Jurídica_ o objeto `brand/companies/businessUnarrangedAccountOverdraft` não está definido como uma lista.

Nas imagens de visão de alto nível das estruturas de dados de ambos os casos, os itens estão sendo tratados como agrupadores. Então podemos concluir que o objeto referente ao _Adiantamento a Depositante Pessoa Natural_ deveria ser um objeto ao invés de uma lista.

Favor verificar o questionamento.

**Comment by luankevinferreira** [comment]
Olá, você poderia registrar sua dúvida no canal oficial de atendimento? https://openbanking-brasil.github.io/suporte/

**Comment by davidburil** [comment]
Ok. Dúvida registrada conforme orientado.

Através do formulário desse link fica menos visível o tratamento dos problemas. 

Não acha que seria mais interessante tratar os problemas em um canal como este que estamos conversando?

**Comment by luankevinferreira** [comment]
Sim, inclusive já levantei esse assunto e também sobre a possibilidade de receber pull requests, algo que ainda não está definido e nem está sendo permitido.
